BASE_URL="https://www.saucedemo.com/"
base_urll="https://www.saucedemo.com/inventory.html"
username_id="user-name"
password_id="password"
login_button_id="login-button"
errorMessage_xpath="//*[@id='login_button_container']/div/form/div[3]/h3"
errorMessage_text="Epic sadface: Username and password do not match any user in this service"
expectedMessage_text="Epic sadface: Username is required"
expectedMessage_xpath="//*[@id='login_button_container']/div/form/div[3]/h3"
standartuser_id="standard_user"
lockeduserout_id="locked_out_user"
secret_sauce_id="secret_sauce"
inventory_item_id="inventory_item"
baslik_xpath="//*[@id='header_container']/div[1]/div[2]/div"
baslik_text="Swag Labs"
